name: GitHub Actions for API Testing gorest.co.in/public/v2
on:
  push:
    branches: [ main, task/checkstyle ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: "Github Actions for NBA-Api-Test"

jobs:
  config_env:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

  test-properties-file:
#    if: github.event_name == 'pull_request'
    name: runner / checkstyle (properties_file)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B verify checkstyle:checkstyle
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: './src/test/resources/config/style/checkstyle-result.xml'

