name: GitHub Actions for API Testing gorest.co.in/public/v2
on:
  push:
    branches: [ main, task/propertie-file ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: "Run Manually"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Read first property
        id: read_first_property
        uses: ./
        with:
          path: './test/resources/config/application-local.properties'
          properties: 'baseURI'
      - name: Do something with the property value
        run: echo ${{ steps.read_first_property.outputs.baseURI }}

#      - name: Show updated file
#        run: cat ${{github.workspace}}/src/test/resources/config/application-local.properties
#        shell: bash
