name: GitHub Actions for API Testing gorest.co.in/public/v2
on:
  push:
    branches: [ main, task/checkstyle ]
  pull_request:
    branches: [ main ]

jobs:
  config_env:
    name: Config Env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  checkstyle:
    name: Exec Checkstyle validation
    runs-on: ubuntu-latest
    needs: [config_env]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - run: mvn checkstyle:check
        continue-on-error: false

